"use client";
import { useActionState } from "react";
import { deleteQuickTemplate, saveQuickTemplate, type SettingsActionState } from "@/app/(private)/settings/actions";
import { dictionaries, type Locale } from "@/lib/i18n/dictionaries";
import type { QuickTransactionTemplate } from "@/lib/finance/types";

type Option={id:string;name:string;active:boolean}; const initial:SettingsActionState={status:"idle",message:""};
function TemplateForm({value,locale,accounts,categories,cards}:{value?:QuickTransactionTemplate;locale:Locale;accounts:Option[];categories:Option[];cards:Option[]}){
 const [state,action,pending]=useActionState(saveQuickTemplate,initial); const t=dictionaries[locale].settings.quickAdd; const tx=dictionaries[locale].transactions;
 return <form action={action} className="mt-3 grid gap-3 rounded-2xl bg-elevated p-3">
  {value?<input type="hidden" name="id" value={value.id}/>:null}<input type="hidden" name="locale" value={locale}/>
  <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm font-black">{t.name}<input name="name" required defaultValue={value?.name} className="rounded-xl border border-line bg-surface px-3 py-2"/></label><label className="grid gap-1 text-sm font-black">{tx.form.type}<select name="type" defaultValue={value?.type??"expense"} className="rounded-xl border border-line bg-surface px-3 py-2"><option value="expense">{tx.types.expense}</option><option value="income">{tx.types.income}</option><option value="credit_card_expense">{tx.types.credit_card_expense}</option></select></label></div>
  <div className="grid grid-cols-2 gap-3"><label className="grid gap-1 text-sm font-black">{t.amount}<input name="amount" type="number" min="0.01" step="0.01" defaultValue={value?.amount??""} placeholder={t.noAmount} className="rounded-xl border border-line bg-surface px-3 py-2"/></label><label className="grid gap-1 text-sm font-black">{t.order}<input name="sort_order" type="number" defaultValue={value?.sort_order??0} className="rounded-xl border border-line bg-surface px-3 py-2"/></label></div>
  <div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-1 text-sm font-black">{t.account}<select name="account_id" defaultValue={value?.account_id??""} className="rounded-xl border border-line bg-surface px-3 py-2"><option value="">{t.choose}</option>{accounts.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-1 text-sm font-black">{t.category}<select name="category_id" defaultValue={value?.category_id??""} className="rounded-xl border border-line bg-surface px-3 py-2"><option value="">{t.choose}</option>{categories.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="grid gap-1 text-sm font-black">{t.card}<select name="related_entity_id" defaultValue={value?.related_entity_id??""} className="rounded-xl border border-line bg-surface px-3 py-2"><option value="">{t.choose}</option>{cards.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div>
  <div className="grid grid-cols-[80px_1fr] gap-3"><label className="grid gap-1 text-sm font-black">{t.icon}<input name="icon_key" maxLength={8} defaultValue={value?.icon_key??"⚡"} className="rounded-xl border border-line bg-surface px-3 py-2"/></label><label className="grid gap-1 text-sm font-black">{t.notes}<input name="notes" defaultValue={value?.notes??""} className="rounded-xl border border-line bg-surface px-3 py-2"/></label></div>
  <label className="flex items-center gap-2 text-sm font-black"><input name="active" type="checkbox" defaultChecked={value?.active??true}/>{value?.active===false?t.disabled:dictionaries[locale].common.active}</label>
  <button disabled={pending} className="min-h-11 rounded-xl bg-primary px-4 font-black text-canvas">{pending?t.saving:t.save}</button>{state.message?<p className={state.status==="success"?"text-income":"text-danger"}>{state.message}</p>:null}
 </form>
}
export function QuickTransactionTemplates({templates,locale,accounts,categories,cards}:{templates:QuickTransactionTemplate[];locale:Locale;accounts:Option[];categories:Option[];cards:Option[]}){const t=dictionaries[locale].settings.quickAdd;return <section className="rounded-panel border border-line bg-surface p-5 shadow-card"><h2 className="text-xl font-black">{t.title}</h2><p className="mt-1 text-sm font-semibold text-muted">{t.description}</p><details className="mt-4"><summary className="cursor-pointer font-black text-primary">+ {t.add}</summary><TemplateForm locale={locale} accounts={accounts} categories={categories} cards={cards}/></details><div className="mt-4 grid gap-3">{templates.map(x=><details key={x.id} className="rounded-2xl border border-line p-3"><summary className="cursor-pointer font-black">{x.icon_key??"⚡"} {x.name} {x.amount?`· ฿${Number(x.amount).toLocaleString()}`:`· ${t.noAmount}`} {!x.active?`· ${t.disabled}`:""}</summary><TemplateForm value={x} locale={locale} accounts={accounts} categories={categories} cards={cards}/><form action={deleteQuickTemplate} className="mt-2"><input type="hidden" name="id" value={x.id}/><button className="text-sm font-black text-danger">{t.delete}</button></form></details>)}</div></section>}
